apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: microservice-architect
build:
  artifacts:
  - image: stepak/otus-microservice-homework1
    context: homework1
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - homework-k8s/deployment.yaml
    - homework-k8s/nginx-ingress.yaml
    - homework-k8s/service.yaml
    - homework-k8s/app-config.yaml
