/**
* User Service
* This is simple client API 
*
* The version of the OpenAPI document: 1.0.0
* Contact: kpote3@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kt3.homework.models


/**
 * 
 * @param code 
 * @param message 
 */
data class Error(
    val code: kotlin.Int,
    val message: kotlin.String
) 

