/**
* User Service
* This is simple client API 
*
* The version of the OpenAPI document: 1.0.0
* Contact: kpote3@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kt3.homework.user.models

/**
 * 
 * @param id 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param phone 
 */
@kotlinx.serialization.Serializable
data class User(
    val id: kotlin.Long? = null,
    val username: kotlin.String? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val email: kotlin.String? = null,
    val phone: kotlin.String? = null
) 

