apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homework1
                port:
                  number: 8000


                  
# spec:
#   ingressClassName: nginx
  
#   rules:
#     - host: arch.homework
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: homework1
#                 port:
#                   number: 8000
            